import joblib
import pandas as pd
import pipeline


# Make the scaling function available in this module.
# This is required when loading a model that was saved with
# scale_passenger as part of its preprocessing pipeline.
scale_passenger = pipeline.scale_passenger

def load_model(model_path):

    """
    Load a previously trained machine-learning model from a file.

    Parameters
    ----------
    model_path : str
        Path to the serialized model file.

    Returns
    -------
    model
        The loaded machine-learning model or pipeline.
    """

    model = joblib.load(model_path)

    return model

def predict(model, X_test):

    """
    Generate predictions for the given input data.

    Parameters
    ----------
    model
        A trained machine-learning model or pipeline with a
        `predict()` method.

    X_test : pandas.DataFrame
        Input features for which predictions should be generated.

    Returns
    -------
    y_pred
        Predictions generated by the model.
    """

    y_pred = model.predict(X_test)

    return y_pred
